### ISSUE TITLE
install routine is not working

### ISSUE THREAD

**Issue by SaibotMagd** [CAIsr/volgenmodel-nipype#7]
I run your install routine and volgenmodel.py stops because of missing mincblur from minc-toolkit v2:

```
Standard error:
Can't exec "mincblur": No such file or directory at /usr/local/bin/mincnorm line 222.
Died at /usr/local/bin/mincnorm line 222.
Return code: 2

210727-09:35:08,621 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 80.00/80.00, Free processors: 8/8.
210727-09:35:10,618 nipype.workflow INFO:
	 ***********************************
210727-09:35:10,618 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,618 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise0-b54cc34a-410a-4104-924c-edfb9a586b92.pklz
210727-09:35:10,619 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,619 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise1-1a479b81-426d-429e-93d5-ff7d8e5b7a0e.pklz
210727-09:35:10,619 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,619 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise2-4fbef6f9-9863-4fd5-80a9-90c253d5ebe4.pklz
210727-09:35:10,619 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,619 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise3-b29c453c-3fbc-48e7-8aae-3f3cdc89eebb.pklz
210727-09:35:10,620 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,620 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise4-1746570d-0b8e-4add-8b47-f0794603c90f.pklz
210727-09:35:10,620 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,620 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise5-7c303db9-8118-4aa5-91a4-2df5db342f80.pklz
210727-09:35:10,620 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,620 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise6-9c39f491-4110-4a3e-9922-6d5d64aa86f4.pklz
210727-09:35:10,621 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,621 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093506-saibotmagd-_preprocess_normalise7-7b7fde07-c0ca-4818-af98-e7a6faf1cebb.pklz
210727-09:35:10,621 nipype.workflow ERROR:
	 could not run node: workflow_temp_workflowMultiProc2.preprocess_normalise
210727-09:35:10,621 nipype.workflow INFO:
	 crashfile: /home/saibotmagd/volgenmodel-nipype/crash-20210727-093508-saibotmagd-_preprocess_normalise8-5553dbc2-20bf-4ad4-9e46-c3f718010a9d.pklz
210727-09:35:10,621 nipype.workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "volgenmodel.py", line 920, in <module>
    wf.run(
  File "/home/saibotmagd/anaconda3/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/saibotmagd/anaconda3/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/home/saibotmagd/anaconda3/lib/python3.8/site-packages/nipype/pipeline/plugins/tools.py", line 96, in report_nodes_not_run
    raise RuntimeError(
RuntimeError: Workflow did not execute cleanly. Check log for details

```

**Comment by stebo85** [comment]
Dear @SaibotMagd - I looks like minc is not correctly installed. How did you install minc?

Could you try executing it inside a container where minc is setup correctly:
 https://bic-mni.github.io/#containers
